name: chat-app
region: eu-central-1
yamlVersion: 2

services:
    databases:
        - name: chat-app
          type: mongo-atlas
backend:
    path: express
    functions:
        - entry: dist/app.js
          handler: handler
          name: serverless
          path: .
          type: aws
    language:
        name: js
    scripts:
        deploy:
            - npm install
            - npm run build
        local:
            - npm install
            - npm run build
frontend:
    environment:
        VITE_API_URL: ${{ backend.functions.serverless.url }}
    path: client
    publish: dist
    scripts:
        build:
            - npm run build
        deploy:
            - npm install
    subdomain: my-chat
